# Generated by Django 5.1.4 on 2025-01-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission_and_calculations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionandgst',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, help_text='Commission rate for the category', max_digits=5),
        ),
    ]
