# Generated by Django 5.1.4 on 2025-01-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission_and_calculations', '0002_alter_commissionandgst_commission_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRangeCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=2, help_text='Minimum price of the range', max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, help_text='Maximum price of the range', max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission rate for this price range (in percentage)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Price Range Commission',
                'verbose_name_plural': 'Price Range Commissions',
            },
        ),
        migrations.DeleteModel(
            name='CommissionAndGST',
        ),
    ]
