# Generated by Django 5.1.4 on 2025-01-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission_and_calculations', '0003_pricerangecommission_delete_commissionandgst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerangecommission',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price of the range (leave blank for no upper limit)', max_digits=10, null=True),
        ),
    ]
