# Generated by Django 5.1.4 on 2025-01-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission_and_calculations', '0004_alter_pricerangecommission_max_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerangecommission',
            name='platform_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Platform charges as a fixed amount for this price range', max_digits=10),
        ),
    ]
