# Generated by Django 5.1.4 on 2025-01-06 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0009_orderitem_order_status'),
        ('commission_and_calculations', '0005_pricerangecommission_platform_charges'),
        ('products', '0007_remove_category_commission_rate'),
        ('vendors', '0003_vendordetails_shop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionAndGST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.DecimalField(decimal_places=2, help_text='Price of the product (inclusive of GST)', max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission rate applied to this product', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Commission amount deducted based on the rate', max_digits=10)),
                ('gst_on_commission', models.DecimalField(decimal_places=2, help_text='GST applied on the commission amount', max_digits=10)),
                ('platform_charges', models.DecimalField(decimal_places=2, help_text='Platform charges for this product', max_digits=10)),
                ('total_deduction', models.DecimalField(decimal_places=2, help_text='Total deductions (commission + GST + platform charges)', max_digits=10)),
                ('vendor_earnings', models.DecimalField(decimal_places=2, help_text='Final earnings for the vendor after all deductions', max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the calculation was performed')),
                ('order_item', models.OneToOneField(help_text='The specific order item linked to these commission details', on_delete=django.db.models.deletion.CASCADE, related_name='commission_details', to='cart_orders.orderitem')),
                ('product', models.ForeignKey(help_text='The product for which these details are calculated', on_delete=django.db.models.deletion.CASCADE, related_name='commission_details', to='products.product')),
                ('vendor', models.ForeignKey(help_text='The vendor who owns the product', on_delete=django.db.models.deletion.CASCADE, related_name='commission_details', to='vendors.vendordetails')),
            ],
        ),
    ]
