# Generated by Django 5.1.4 on 2024-12-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0002_order_orderitem_suborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='The date and time when the last reminder email was sent.', null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the cart was created.'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the cart was last updated.'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the item was added to the cart.'),
        ),
    ]
