# Generated by Django 5.1.4 on 2024-12-26 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0003_address'),
        ('cart_orders', '0003_cart_last_reminder_sent_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, help_text='The address used for this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='authusers.address'),
        ),
    ]
