# Generated by Django 5.1.4 on 2024-12-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0007_remove_deliverydetail_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', help_text='Payment status for the order.', max_length=10),
        ),
    ]
