# Generated by Django 5.1.4 on 2025-01-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0008_orderitem_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('packed', 'Packed'), ('ready_to_pick_up', 'Ready to Pick Up')], default='confirmed', help_text='Status of the order item.', max_length=20),
        ),
    ]
