# Generated by Django 5.1.4 on 2025-01-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0009_orderitem_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod_payment_received',
            field=models.BooleanField(default=False, help_text='Indicates whether COD payment has been received.'),
        ),
        migrations.AddField(
            model_name='order',
            name='cod_remittance_date',
            field=models.DateField(blank=True, help_text='Date when COD payment was remitted.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('placed', 'Order Placed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='placed', help_text='Current status of the order.', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cod_pending', 'COD Pending'), ('cod_paid', 'COD Paid'), ('cancelled', 'Cancelled')], default='pending', help_text='Payment status for the order.', max_length=15),
        ),
    ]
