# Generated by Django 5.1.4 on 2025-01-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0011_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='dellivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
