# Generated by Django 5.1.4 on 2025-01-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0012_orderitem_dellivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='dellivery_date',
            new_name='delivery_date',
        ),
    ]
