# Generated by Django 5.1.4 on 2025-01-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0014_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('packed', 'Packed'), ('warehouse', 'Warehouse'), ('shiped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='confirmed', help_text='Status of the order item.', max_length=20),
        ),
    ]
