# Generated by Django 5.1.4 on 2025-01-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0015_alter_orderitem_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='delivery date', null=True),
        ),
    ]
