# Generated by Django 5.1.4 on 2025-01-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Image for the banner', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='scrollablebanner',
            name='image',
            field=models.ImageField(help_text='Image for the scrollable banner', null=True, upload_to='scrollable_banners/'),
        ),
    ]
