# Generated by Django 5.1.4 on 2025-01-07 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart_orders', '0010_order_cod_payment_received_order_cod_remittance_date_and_more'),
        ('vendors', '0003_vendordetails_shop_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Description of the action performed', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('user', models.ForeignKey(blank=True, help_text='Admin who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount', max_digits=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='initiated', help_text='Status of the refund', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the refund was processed', null=True)),
                ('reason', models.TextField(help_text='Reason for the refund')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the refund was created')),
                ('order', models.ForeignKey(help_text='Order associated with the refund', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='cart_orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='VendorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payout amount', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed')], default='pending', help_text='Status of the payout', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the payout was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the payout was created')),
                ('vendor', models.ForeignKey(help_text='Vendor receiving the payout', on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='vendors.vendordetails')),
            ],
        ),
    ]
