# Generated by Django 5.1.4 on 2025-01-07 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='customer',
            field=models.ForeignKey(
                help_text='Customer requesting the refund',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='refund_requests',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='refund',
            name='requested_at',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='When the refund was requested'
            ),
        ),
    ]
