# Generated by Django 5.1.4 on 2025-01-13 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_refund_customer_refund_requested_at'),
        ('cart_orders', '0012_orderitem_dellivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='order',
        ),
        migrations.AddField(
            model_name='refund',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='Order associated with the refund', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='cart_orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('approved', 'Approved'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='initiated', help_text='Status of the refund', max_length=20),
        ),
    ]
