# Generated by Django 5.1.4 on 2025-01-14 23:04

import admin_portal.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0003_remove_refund_order_refund_order_item_and_more'),
        ('cart_orders', '0013_rename_dellivery_date_orderitem_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='requested_at',
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_implemented_date',
            field=models.DateTimeField(blank=True, help_text='Date when the refund was implemented', null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_initiated_date',
            field=models.DateTimeField(blank=True, help_text='Date when the refund was initiated', null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_processed_date',
            field=models.DateTimeField(blank=True, help_text='Date when the refund was processed', null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_rejected_date',
            field=models.DateTimeField(blank=True, help_text='Date when the refund was rejected', null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the refund was last updated'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Refund amount for the order item', max_digits=10),
        ),
        migrations.AlterField(
            model_name='refund',
            name='order_item',
            field=models.ForeignKey(help_text='Order item for which the refund is requested', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='cart_orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('initiated', 'Refund Initiated'), ('processed', 'Refund Processed'), ('rejected', 'Refund Rejected'), ('implemented', 'Refund Implemented')], default='initiated', help_text='Current status of the refund', max_length=15),
        ),
        migrations.CreateModel(
            name='RefundMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(help_text='Image or video file supporting the refund request', upload_to=admin_portal.models.refund_media_upload_path)),
                ('refund', models.ForeignKey(help_text='The refund associated with this media', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='admin_portal.refund')),
            ],
        ),
    ]
