# Generated by Django 5.1.4 on 2025-01-14 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0004_remove_refund_customer_remove_refund_processed_at_and_more'),
        ('cart_orders', '0013_rename_dellivery_date_orderitem_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='refund',
            name='reason',
            field=models.TextField(default='__________', help_text='Reason provided by the customer for the refund.'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Refund amount for the order item.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='refund',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date when the refund was created.'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='order_item',
            field=models.ForeignKey(help_text='The order item for which the refund is requested.', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='cart_orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_implemented_date',
            field=models.DateTimeField(blank=True, help_text='The date when the refund was implemented.', null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_initiated_date',
            field=models.DateTimeField(blank=True, help_text='The date when the refund was initiated.', null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_processed_date',
            field=models.DateTimeField(blank=True, help_text='The date when the refund was processed.', null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_rejected_date',
            field=models.DateTimeField(blank=True, help_text='The date when the refund was rejected.', null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('initiated', 'Refund Initiated'), ('processed', 'Refund Processed'), ('rejected', 'Refund Rejected'), ('implemented', 'Refund Implemented')], default='initiated', help_text='Current status of the refund.', max_length=20),
        ),
    ]
