# Generated by Django 5.1.4 on 2025-01-21 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0005_remove_refund_updated_at_refund_reason_and_more'),
        ('cart_orders', '0015_alter_orderitem_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField(help_text='Pickup address provided by admin')),
                ('shipping_address', models.TextField(help_text='Fetched from the order')),
                ('tracking_id', models.CharField(blank=True, help_text='Tracking ID from Delhivery', max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', help_text='Payment status for the order', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of the order in kilograms', max_digits=6)),
                ('dimensions', models.JSONField(help_text='Dimensions of the order (length, breadth, height) in cm')),
                ('serviceability_checked', models.BooleanField(default=False, help_text='Indicates if serviceability check is done')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_data', to='cart_orders.order')),
            ],
        ),
    ]
