# Generated by Django 5.1.4 on 2025-01-23 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0007_warehouseaddress'),
        ('cart_orders', '0015_alter_orderitem_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='XpressBeeShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpressbees_awb_number', models.CharField(blank=True, help_text='Xpressbees AWB number', max_length=50, null=True)),
                ('status', models.CharField(default='pending', help_text='Shipment status', max_length=50)),
                ('package_weight', models.FloatField()),
                ('package_length', models.FloatField()),
                ('package_breadth', models.FloatField()),
                ('package_height', models.FloatField()),
                ('payment_type', models.CharField(choices=[('cod', 'Cash on Delivery'), ('prepaid', 'Prepaid'), ('reverse', 'Reverse')], max_length=10)),
                ('shipping_charges', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('cod_charges', models.FloatField(blank=True, null=True)),
                ('order_amount', models.FloatField()),
                ('collectable_amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xpress_bees', to='cart_orders.order')),
            ],
        ),
    ]
