# Generated by Django 5.1.4 on 2025-01-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0008_xpressbeeshipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpressbeeshipment',
            name='cod_charges',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='xpressbeeshipment',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='xpressbeeshipment',
            name='shipping_charges',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
