# Generated by Django 5.1.4 on 2025-01-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0009_alter_xpressbeeshipment_cod_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpressbeeshipment',
            name='order_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
