# Generated by Django 5.1.4 on 2025-02-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0010_alter_xpressbeeshipment_order_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='created_at',
            new_name='refund_request_date',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='refund_implemented_date',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='refund_initiated_date',
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('initiated', 'Refund Initiated'), ('approved', 'Approved'), ('in_transit', 'In_Transit'), ('processed', 'Refund Processed'), ('rejected', 'Refund Rejected'), ('implemented', 'Refund Implemented')], default='initiated', help_text='Current status of the refund.', max_length=20),
        ),
    ]
