# Generated by Django 5.1.4 on 2024-12-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendordetails_address_vendordetails_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
