# Generated by Django 5.1.4 on 2025-01-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productvariant_variant_images_variantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cancellation_stage',
            field=models.CharField(blank=True, choices=[('pre-shipping', 'Before Shipping'), ('post-shipping', 'After Shipping')], help_text='Stage at which cancellation is allowed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_cancelable',
            field=models.BooleanField(default=True, help_text='Can this product be canceled?'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_cod_allowed',
            field=models.BooleanField(default=True, help_text='Is cash on delivery allowed for this product?'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=False, help_text='Can this product be returned?'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_return_days',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum return days (if returnable)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed product description', null=True),
        ),
    ]
