# Generated by Django 5.1.4 on 2025-01-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_cancellation_stage_product_is_cancelable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cancellation_stage',
            field=models.CharField(blank=True, choices=[('before_packing', 'Before Packing'), ('before_shipping', 'Before Shipping'), ('before_delivery', 'Before Delivery')], help_text='Stage at which cancellation is allowed', max_length=50, null=True),
        ),
    ]
