# Generated by Django 5.1.4 on 2025-01-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission rate (in percentage) for this category', max_digits=5),
        ),
    ]
