# Generated by Django 5.1.4 on 2025-01-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_commission_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='commission_rate',
        ),
    ]
