# Generated by Django 5.1.4 on 2025-01-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_featuredproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='Icon image for the category', null=True, upload_to='category_icons/'),
        ),
    ]
